test

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -16,13 +16,14 @@ jobs:
         run: |
           start_time=$(date -Iminutes)
           echo "$start_time" > log.txt
-          echo "Your Name" >> log.txt
+          echo "Bar Volovski, Omer Bar-Yehuda" >> log.txt
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
       - name: Build Docker image
         id: docker_build
+        continue-on-error: true
         uses: docker/build-push-action@v5
         with:
           context: ./books-service
@@ -53,6 +54,10 @@ jobs:
           name: log-file
           path: log.txt
 
+      - name: Fail the job if Docker build failed
+        if: steps.docker_build.outcome != 'success'
+        run: exit 1
+
   test:
     needs: build
     runs-on: ubuntu-latest
@@ -81,7 +86,7 @@ jobs:
             echo "Container up and running" >> log.txt
           else
             echo "Container failed to run" >> log.txt
-            exit 1
+            exit 1  # Exit if Docker Compose fails to start the containers
           fi
 
       - name: Set up Python
@@ -93,7 +98,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install pytest requests
-
+      
       - name: Run tests
         id: run_tests
         run: |
@@ -106,6 +111,7 @@ jobs:
             echo "tests succeeded" >> log.txt
           else
             echo "tests failed" >> log.txt
+            exit 1  # This will fail the job if tests failed
           fi
 
       - name: Upload test results
@@ -121,6 +127,10 @@ jobs:
           name: log-file
           path: log.txt
           overwrite: true
+
+      - name: Stop Docker Compose
+        if: always()
+        run: docker compose down
 
   query:
     needs: test
