test result bug

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -98,14 +98,16 @@ jobs:
       - name: Run tests
         id: run_tests
         run: |
-          pytest -v books-service/tests/assn3_tests.py > assn3_test_results.txt || true
+          pytest -v books-service/tests/assn3_tests.py > assn3_test_results.txt
+        continue-on-error: true
 
       - name: Log test results and update log file
         run: |
-          if grep -q "FAILED" assn3_test_results.txt; then
-            echo "tests failed" >> log.txt
-          else
+          if [ "${{ steps.run_tests.outcome }}" == "success" ]; then
             echo "tests succeeded" >> log.txt
+          else
+            echo "tests failed" >> log.txt
+            exit 1  # This will fail the job if tests failed
           fi
 
       - name: Upload test results
@@ -124,16 +126,12 @@ jobs:
           overwrite: true
 
       - name: Stop Docker Compose
-        run: docker compose down
         if: always()
-
-      - name: Exit if tests failed
-        if: failure()
-        run: exit 1
+        run: docker compose down
 
   query:
     needs: test
-    if: success()  # This ensures that the query job only runs if the test job succeeds
+    if: success()
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -212,4 +210,5 @@ jobs:
           path: response.txt
 
       - name: Stop Docker Compose
+        if: always()
         run: docker compose down
