test

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -1,86 +1,184 @@
-name: assignment3
-
-on:
-  push:
-    branches:
-      - main
-
+name: Build, Test, and Query
+on: push
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - name: Checkout
+        uses: actions/checkout@v4
 
+      - name: Creating log file
+        run: |
+          echo "$(date -Iminutes)" > log.txt
+          echo "Bar Volovski" >> log.txt
+      
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
+        uses: docker/setup-buildx-action@v3
 
-      - name: Build the Docker image
-        run: docker-compose -f books-service/docker-compose.yml build
+      - name: Build and export
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: ./BooksService/Dockerfile
+          tags: books-service:latest, ${{ secrets.DOCKER_COURSE_USERNAME }}/books-service:latest
+          outputs: type=docker, dest=/tmp/books_image.tar
 
-      - name: Save build result to log.txt
-        run: echo "image successfully built" > log.txt
+      - name: Uploading image artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: books-service-image
+          path: /tmp/books_image.tar
+
+      - name: Log build success
+        run: echo "image successfully built" >> log.txt
         if: success()
 
-      - name: Upload build log
-        uses: actions/upload-artifact@v2
+      - name: Log build failure
+        run: echo "image not able to be built" >> log.txt
+        if: failure()
+
+      - name: Uploading log artifact
+        if: always()
+        uses: actions/upload-artifact@v4
         with:
-          name: build-log
+          name: workflow-log
           path: log.txt
 
   test:
-    runs-on: ubuntu-latest
     needs: build
-    services:
-      mongo:
-        image: mongo:latest
-        ports:
-          - 27017:27017
-
+    runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - name: Checkout
+        uses: actions/checkout@v4
 
-      - name: Run Docker Compose
-        run: docker-compose -f books-service/docker-compose.yml up -d
+      - name: Downloading log artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: workflow-log
+          path: ./
 
-      - name: Run pytest tests
+      - name: Downloading Books Service image artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: books-service-image
+          path: ./
+
+      - name: Load Books Service image
+        run: docker load --input books_image.tar
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Building with Docker Compose
+        run: docker compose up -d
+        continue-on-error: true
+
+      - name: Check build status
+        id: build_status
+        run: echo "BUILD_STATUS=$?" >> $GITHUB_ENV
+
+      - name: Handling failure build
+        if: env.BUILD_STATUS != '0'
+        run: exit 1
+
+      - name: Handling successful build
+        if: success()
+        run: echo "Container up and running" >> log.txt
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+
+      - name: Install dependencies
         run: |
-          docker exec -it books-service_web_1 pytest -v tests/assn3_tests.py | tee assn3_test_results.txt
+          python -m pip install --upgrade pip
+          pip install pytest
+          pip install requests
+      
+      - name: Run tests
+        run: pytest -v tests/assn3_tests.py > assn3_test_results.txt
+      
+      - name: Log test results
+        if: always()
+        run: |
+          if grep -q "failed" assn3_test_results.txt; then
+            echo "tests failed" >> log.txt
+          else
+            echo "tests succeeded" >> log.txt
+          fi
 
       - name: Upload test results
-        uses: actions/upload-artifact@v2
+        if: always()
+        uses: actions/upload-artifact@v4
         with:
           name: test-results
           path: assn3_test_results.txt
 
-  query:
-    runs-on: ubuntu-latest
-    needs: test
-    services:
-      mongo:
-        image: mongo:latest
-        ports:
-          - 27017:27017
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Run Docker Compose
-        run: docker-compose -f books-service/docker-compose.yml up -d
-
-      - name: Run queries and save output
-        run: |
-          while IFS= read -r query; do
-            response=$(curl -s "http://localhost:5001/books$query")
-            echo "query: $query" >> response.txt
-            echo "response: $response" >> response.txt
-          done < query.txt
-
-      - name: Upload query results
-        uses: actions/upload-artifact@v2
+      - name: Uploading log artifact
+        if: always()
+        uses: actions/upload-artifact@v4
         with:
-          name: query-results
-          path: response.txt
+          name: workflow-log
+          path: log.txt
+          overwrite: true
+    
+  query:
+    needs: test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
 
+      - name: Downloading Books Service image artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: books-service-image
+          path: ./
+
+      - name: Load Books Service image
+        run: docker load --input books_image.tar
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Building with Docker Compose
+        run: docker compose up --build -d
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+
+      - name: Checking that the containers are up
+        run: docker ps
+
+      - name: Posting books 1, 2, 3, 6, 7, 8
+        run:  |
+          curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "Adventures of Huckleberry Finn", "ISBN": "9780520343641", "genre": "Fiction"}'
+          curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "The Best of Isaac Asimov", "ISBN": "9780385050784", "genre": "Science Fiction"}'
+          curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "Fear No Evil", "ISBN": "9780394558783", "genre": "Biography"}'
+          curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "The Adventures of Tom Sawyer", "ISBN": "9780195810400", "genre": "Fiction"}'
+          curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "I, Robot", "ISBN": "9780553294385", "genre": "Science Fiction"}'
+          curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "Second Foundation", "ISBN": "9780553293364", "genre": "Science Fiction"}'
+
+      - name: Reading and executing query.txt queries
+        run: |
+          if [ ! -e "query.txt" ]; then
+            echo "File not found!" >> response.txt
+            exit 0
+          fi
+          while IFS= read -r line
+          do
+            echo "query: $line" >> response.txt
+            url="http://127.0.0.1:5001/books$line"
+            res=$(curl --location --request GET "$url")
+            echo "response: $res" >> response.txt
+          done < "query.txt"
+      
+      - name: Upload response.txt file
+        uses: actions/upload-artifact@v4
+        with:
+          name: queries-response
+          path: response.txt
