Update logfile

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -30,23 +30,23 @@ jobs:
           tags: books-service:latest
           outputs: type=docker,dest=/tmp/books-service.tar
       
-      - name: Log image build result if failed
-        if: failure()
-        run: echo "image not able to be built" >> log.txt
+      - name: Log image build result
+        run: |
+          if [ -f "/tmp/books-service.tar" ]; then
+            echo "image successfully built" >> log.txt
+          else
+            echo "image not able to be built" >> log.txt
+          fi
 
-      - name: Log image build result if success
-        if: success()
-        run: echo "image successfully built" >> log.txt
-         
       - name: Upload Docker image as artifact
-        if: success()
         uses: actions/upload-artifact@v4
+        if: success()
         with:
           name: books-service
           path: /tmp/books-service.tar
 
-      - name: Upload build log
-        if: always()    
+      - name: Upload build log if image build fails
+        if: failure()
         uses: actions/upload-artifact@v4
         with:
           name: log
@@ -69,12 +69,13 @@ jobs:
         run: docker load --input /tmp/books-service.tar
 
       - name: Set up Docker Compose
-        run: docker compose -f docker-compose.yml up -d
+        run: |
+          docker compose -f docker-compose.yml up -d && echo "Container up and running" >> log.txt || echo "Container failed to run" >> log.txt
 
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version: '3.9'  # Specify the Python version
+          python-version: '3.9'
 
       - name: Install dependencies
         run: |
@@ -83,11 +84,10 @@ jobs:
       
       - name: Run tests
         run: |
-          pytest -v books-service/tests/assn3_tests.py > assn3_test_results.txt
+          pytest -v books-service/tests/assn3_tests.py > assn3_test_results.txt || true
         continue-on-error: true  # This allows the workflow to continue even if tests fail
       
       - name: Log test results
-        if: always()
         run: |
           if grep -q "FAILED" assn3_test_results.txt; then
             echo "tests failed" >> log.txt
@@ -96,14 +96,12 @@ jobs:
           fi
 
       - name: Upload test results
-        if: always()    
         uses: actions/upload-artifact@v4
         with:
           name: test-results
           path: assn3_test_results.txt
 
       - name: Upload updated build log
-        if: always()    
         uses: actions/upload-artifact@v4
         with:
           name: log
