test

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -1,55 +1,51 @@
-name: assignment3
-on:
-  push:
+name: Build, Test, and Query
+
+on: push
+
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Insert to log file start time and submitters names
-        run: echo -e "$(date -Iminutes)\nbarv" > /tmp/log.txt
-
-      - name: Print Log File Contents 
-        run: cat /tmp/log.txt 
-
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Setup Docker Buildx
+      - name: Creating log file
+        run: |
+          echo "$(date -Iminutes)" > log.txt
+          echo "bar" >> log.txt
+
+      - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
       - name: Build and export
         uses: docker/build-push-action@v5
         with:
-          context: ./books-services
-          tags: books:latest
-          outputs: type=docker,dest=/tmp/image.tar
+          context: books-service
+          file: books-service/Dockerfile
+          tags: books-service:latest
+          outputs: type=docker, dest=/tmp/books_image.tar
 
-      - name: Handle build failure
-        if: failure()
-        run: |
-          echo -e "image not able to be built" >> /tmp/log.txt
+      - name: Uploading image artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: books-service-image
+          path: /tmp/books_image.tar
 
-      - name: Handle build success
+      - name: Log build success
+        run: echo "image successfully built" >> log.txt
         if: success()
-        run: |
-          echo -e "image successfully built" >> /tmp/log.txt
 
-      - name: Print log file contents 
-        run: cat /tmp/log.txt 
+      - name: Log build failure
+        run: echo "image not able to be built" >> log.txt
+        if: failure()
 
-      - name: Upload log file
+      - name: Uploading log artifact
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: log
-          path: /tmp/log.txt
+          name: workflow-log
+          path: log.txt
 
-      - name: Upload artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: books
-          path: /tmp/image.tar
-        
   test:
     needs: build
     runs-on: ubuntu-latest
@@ -57,152 +53,134 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Download books artifact
+      - name: Downloading log artifact
         uses: actions/download-artifact@v4
         with:
-          name: books
-          path: /tmp
+          name: workflow-log
+          path: ./
 
-      - name: Load Docker images from previous workflows
-        run: docker load --input /tmp/image.tar
-
-      - name: Download log artifact
+      - name: Downloading Books Service image artifact
         uses: actions/download-artifact@v4
         with:
-          name: log
-          path: /tmp
+          name: books-service-image
+          path: ./
 
-      - name: Print log file contents # this is for check only
-        run: cat /tmp/log.txt # this is for check only
+      - name: Load Books Service image
+        run: docker load --input books_image.tar
 
-      - name: Check if books image is loaded
-        run: docker image ls
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-      - name: Start Docker Container
+      - name: Building with Docker Compose
+        run: docker compose -f docker-compose.yml up -d
+        continue-on-error: true
+
+      - name: Check build status
+        id: build_status
+        run: echo "BUILD_STATUS=$?" >> $GITHUB_ENV
+
+      - name: Handling failure build
+        if: env.BUILD_STATUS != '0'
+        run: exit 1
+
+      - name: Handling successful build
         if: success()
-        run: docker compose up -d || true
-
-      - name: Wait for Container to Start
-        if: success()
-        run: sleep 10
-
-      - name: Check Container Status
-        if: success()
-        run: |
-          if docker ps --filter "name=books" --filter "status=running" | grep books; then
-            echo "Container up and running" >> /tmp/log.txt
-            echo "containers_running=true" >> $GITHUB_ENV
-          else
-            echo "Container failed to run" >> /tmp/log.txt
-            echo "containers_running=false" >> $GITHUB_ENV
-          fi
-
-      - name: Print log file contents # this is for check only
-        run: cat /tmp/log.txt # this is for check only
+        run: echo "Container up and running" >> log.txt
 
       - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: 3.9
+        uses: actions/setup-python@v5
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install pytest
           pip install requests
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-
-      - name: Run pytest tests
-        run: |
-          cd tests
-          pytest -v assn3_tests.py > assn3_test_results.txt
-
-      - name: Handle tests failure
-        if: failure() && env.containers_running == 'true'
-        run: echo -e "tests failed" >> /tmp/log.txt
-
-      - name: Handle tests success
-        if: success() && env.containers_running == 'true'
-        run: echo -e "tests succeeded" >> /tmp/log.txt
-
-      - name: Upload test results to the requested file
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: assn3_test_results
-          path: tests/assn3_test_results.txt
-
-      - name: Upload log file
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: log
-          path: /tmp/log.txt
-          overwrite: true
-
-      - name: Shut down Docker Compose
-        if: always()
-        run: docker compose down
       
+      - name: Run tests
+        run: pytest -v books-service/tests/assn3_tests.py > assn3_test_results.txt
+      
+      - name: Log test results
+        if: always()
+        run: |
+          if grep -q "failed" assn3_test_results.txt; then
+            echo "tests failed" >> log.txt
+          else
+            echo "tests succeeded" >> log.txt
+          fi
+
+      - name: Upload test results
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-results
+          path: assn3_test_results.txt
+
+      - name: Uploading log artifact
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: workflow-log
+          path: log.txt
+          overwrite: true
+    
   query:
     needs: test
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    - name: Download books image artifact
-      uses: actions/download-artifact@v4
-      with:
-        name: books
-        path: /tmp
+      - name: Downloading Books Service image artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: books-service-image
+          path: ./
 
-    - name: Load Docker image
-      run: docker load --input /tmp/image.tar
+      - name: Load Books Service image
+        run: docker load --input books_image.tar
 
-    - name: Download log file
-      uses: actions/download-artifact@v4
-      with:
-        name: log
-        path: /tmp
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-    - name: Start Docker Compose
-      run: docker compose up -d
+      - name: Building with Docker Compose
+        run: docker compose -f docker-compose.yml up --build -d
 
-    - name: Wait for application to start
-      run: sleep 10
+      - name: Set up Python
+        uses: actions/setup-python@v5
 
-    - name: Execute POST requests
-      run: |
-        curl -X POST -H "Content-Type: application/json" -d '{"title": "Adventures of Huckleberry Finn", "ISBN": "9780520343641", "genre": "Fiction"}' http://localhost:5001/books
-        curl -X POST -H "Content-Type: application/json" -d '{"title": "The Best of Isaac Asimov", "ISBN": "9780385050784", "genre": "Science Fiction"}' http://localhost:5001/books
-        curl -X POST -H "Content-Type: application/json" -d '{"title": "Fear No Evil", "ISBN": "9780394558783", "genre": "Biography"}' http://localhost:5001/books
-        curl -X POST -H "Content-Type: application/json" -d '{"title": "The Adventures of Tom Sawyer", "ISBN": "9780195810400", "genre": "Fiction"}' http://localhost:5001/books
-        curl -X POST -H "Content-Type: application/json" -d '{"title": "I, Robot", "ISBN": "9780553294385", "genre": "Science Fiction"}' http://localhost:5001/books
-        curl -X POST -H "Content-Type: application/json" -d '{"title": "Second Foundation", "ISBN": "9780553293364", "genre": "Science Fiction"}' http://localhost:5001/books
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r books-service/requirements.txt
 
-    - name: Set up Python
-      uses: actions/setup-python@v4
-      with:
-        python-version: 3.9
+      - name: Checking that the containers are up
+        run: docker ps
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install pytest
-        pip install requests
+      - name: Posting books 1, 2, 3, 6, 7, 8
+        run:  |
+          curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "Adventures of Huckleberry Finn", "ISBN": "9780520343641", "genre": "Fiction"}'
+          curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "The Best of Isaac Asimov", "ISBN": "9780385050784", "genre": "Science Fiction"}'
+          curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "Fear No Evil", "ISBN": "9780394558783", "genre": "Biography"}'
+          curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "The Adventures of Tom Sawyer", "ISBN": "9780195810400", "genre": "Fiction"}'
+          curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "I, Robot", "ISBN": "9780553294385", "genre": "Science Fiction"}'
+          curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "Second Foundation", "ISBN": "9780553293364", "genre": "Science Fiction"}'
 
-    - name: run query
-      run: |
-        cd tests
-        python run_query.py
- 
-    - name: Upload response file
-      uses: actions/upload-artifact@v4
-      with:
-        name: response
-        path: tests/response.txt
-
-    - name: Shut down Docker Compose
-      if: always()
-      run: docker compose down
+      - name: Reading and executing query.txt queries
+        run: |
+          if [ ! -e "books-service/query.txt" ]; then
+            echo "File not found!" >> response.txt
+            exit 0
+          fi
+          while IFS= read -r line
+          do
+            echo "query: $line" >> response.txt
+            url="http://127.0.0.1:5001/books$line"
+            res=$(curl --location --request GET "$url")
+            echo "response: $res" >> response.txt
+          done < "books-service/query.txt"
+      
+      - name: Upload response.txt file
+        uses: actions/upload-artifact@v4
+        with:
+          name: queries-response
+          path: response.txt
